{ pkgs, config, lib, ... }:
with lib;

let
  cfg = config.jd.desktop;
  systemCfg = config.machineData.systemConfig;
in {
  options.jd.desktop = {
    type = mkOption {
      description = ''What desktop/wm to use. Options: "dwm"'';
      type = types.enum [ "dwm" ];
      default = null;
    };

    screenlock = {
      enable = mkOption {
        description = "Enable screen locking (xss-lock). Only used with dwm";
        type = types.bool;
        default = false;
      };

      timeout = {
        script = mkOption {
          description = "Script to run on timeout. Default null";
          type = with types; nullOr package;
          default = null;
        };

        time = mkOption {
          description = "Time in seconds until run timeout script. Default 180.";
          type = types.int;
          default = 180;
        };
      };

      lock = {
        command = mkOption {
          description = "Lock command. Default xsecurelock";
          type = types.str;
          default = "${pkgs.xsecurelock}/bin/xsecurelock";
        };

        time = mkOption {
          description = "Time in seconds after timeout until lock. Default 180.";
          type = types.int;
          default = 180;
        };
      };
    };
  };

  config = (
    let
      isStartX = (systemCfg.xserver.enable && (systemCfg.xserver.display-manager.type == "startx"));
      startCommand = "${pkgs.dwmJD}/bin/dwm";
    in {
      home.packages = mkIf (cfg.type == "dwm") (with pkgs; [
        dwmJD stJD dmenu xbindkeys pavucontrol pulsemixer
      ]);

      home.file.".xinitrc" = mkIf (isStartX) {
        executable = true;
        text = ''
          # .xinitrc autogenerated. Do not edit
          . "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh"

          if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
            eval $(dbus-launch --exit-with-session --sh-syntax)
          fi
          
          systemctl --user import-environment DISPLAY XAUTHORITY XDG_SESSION_ID PATH
          
          if command -v dbus-update-activation-environment >/dev/null 2>&1; then
            dbus-update-activation-environment DISPLAY XAUTHORITY
          fi

          systemctl --user start graphical-session.target

          xset s ${toString cfg.screenlock.timeout.time} ${toString cfg.screenlock.lock.time}
          ${pkgs.xbindkeys}/bin/xbindkeys
          ${startCommand}

          systemctl --user stop graphical-session.target
          systemctl --user stop graphical-session-pre.target

          # Wait until the units actually stop.
          while [ -n "$(systemctl --user --no-legend --state=deactivating list-units)" ]; do
            sleep 0.5
          done
        '';
      };

      home.file.".xbindkeysrc" = mkIf (cfg.type == "dwm") {
        text = ''
          # Mute volume
          "pactl set-sink-mute @DEFAULT_SINK@ toggle"
            XF86AudioMute
          # Raise volume
          "pulsemixer --change-volume +2 --max-volume 150"
            XF86AudioRaiseVolume
          # Lower volume
          "pactl set-sink-volume @DEFAULT_SINK@ -2%"
            XF86AudioLowerVolume
          # Mute microphone
          "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
            XF86AudioMicMute
        '';
      };

      systemd = mkIf (cfg.type == "dwm" && cfg.screenlock.enable) {
        user.services = {
          xss-lock = {
            Install = {
              WantedBy = [ "graphical-session.target" ];
            };

            Unit = {
              Description = "XSS Lock Daemon";
              PartOf = [ "graphical-session.target" ];
              After = [ "graphical-session.target" ];
            };

            Service = {
              ExecStart = "${pkgs.xss-lock}/bin/xss-lock -s \${XDG_SESSION_ID} ${if cfg.screenlock.timeout.script == null then "" else "-n ${cfg.screenlock.timeout.script}"} -l -- ${cfg.screenlock.lock.command}";
            };
          };
        };
      };
    
      services.gnome-keyring.enable = true;

      gtk = {
        enable = true;
        theme = {
          package = with pkgs; arc-theme;
          name = "Arc-Dark";
        };
      };
    }
  );
}
