{ lib, ... }@args:
with lib;
{
    home.file.".xinitrc" = {
      executable = true;
      text = ''
        # .xinitrc autogenerated. Do not edit

        if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
          eval $(dbus-launch --exit-with-session --sh-syntax)
        fi
        
        systemctl --user import-environment DISPLAY XAUTHORITY XDG_SESSION_ID
        
        if command -v dbus-update-activation-environment >/dev/null 2>&1; then
          dbus-update-activation-environment DISPLAY XAUTHORITY
        fi

        systemctl --user start graphical-session.target

        xset s 180 300
        ${args.startCommand}

        systemctl --user stop graphical-session.target
        systemctl --user stop graphical-session-pre.target

        # Wait until the units actually stop.
        while [ -n "$(systemctl --user --no-legend --state=deactivating list-units)" ]; do
          sleep 0.5
        done
      '';
    };
 
}
